# Generated by Django 5.2.6 on 2025-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="tipo_questao",
            field=models.CharField(
                choices=[
                    ("RESPOSTA_UNICA", "Resposta Única"),
                    ("MULTIPLA_ESCOLHA", "Resposta Múltipla"),
                    ("ASSERCAO_RAZAO", "Asserção-Razão"),
                ],
                default="RESPOSTA_UNICA",
                max_length=20,
            ),
        ),
    ]
