# Generated by Django 5.2.6 on 2025-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0002_questao_tipo_questao"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="proposicao_dois",
            field=models.TextField(
                blank=True,
                help_text="A segunda proposição para questões do tipo Asserção-Razão.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="eh_correta",
            field=models.BooleanField(
                default=False,
                help_text="Marque se for a alternativa correta (Resposta Única) ou a afirmativa correta (Resposta Múltipla).",
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="texto",
            field=models.CharField(
                help_text="Texto da alternativa ou da afirmativa (para Resposta Múltipla).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="enunciado",
            field=models.TextField(
                help_text="O enunciado ou a primeira proposição da questão."
            ),
        ),
    ]
