# Generated by Django 5.2.6 on 2025-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questoes",
            "0003_questao_proposicao_dois_alter_alternativa_eh_correta_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="comentario_validacao",
            field=models.TextField(
                blank=True,
                help_text="Comentário do administrador ao aprovar ou reprovar a questão.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="professor_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail do professor para notificações de status.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="professor_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome do professor que elaborou a questão.",
                max_length=200,
                null=True,
            ),
        ),
    ]
