# Generated by Django 5.2.6 on 2025-10-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questoes",
            "0004_questao_comentario_validacao_questao_professor_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Um nome para identificar o prompt, ex: 'Avaliação Padrão de Questões'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "texto_prompt",
                    models.TextField(
                        help_text="O texto completo do prompt a ser enviado para a IA. Use chaves {} para variáveis, ex: {texto_base}."
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para usar este prompt. Apenas um pode estar ativo.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt para IA",
                "verbose_name_plural": "Prompts para IA",
            },
        ),
    ]
