# Generated by Django 5.2.6 on 2025-10-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0005_aiprompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="justificativa",
            field=models.TextField(
                blank=True,
                help_text="Explicação detalhada sobre o gabarito e as alternativas.",
                null=True,
            ),
        ),
    ]
