# Generated by Django 5.1.3 on 2025-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0006_alter_questao_justificativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="uso_prova",
            field=models.CharField(
                choices=[
                    ("INTEGRADA", "Apenas Prova Integrada"),
                    ("REPOSICAO", "Apenas Prova de Reposição"),
                    ("AMBAS", "Integrada E Reposição"),
                ],
                default="INTEGRADA",
                help_text="Indique se a questão pode ser usada na Integrada, Reposição ou em ambas.",
                max_length=10,
            ),
        ),
    ]
