# Generated by Django 5.1.3 on 2026-02-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0008_alter_questao_uso_prova"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="uso_prova",
            field=models.CharField(
                choices=[
                    ("INTEGRADA", "Apenas Prova Integrada"),
                    ("REPOSICAO", "Apenas Prova de Reposição"),
                    ("RESIDENCIA", "Prova de Residência Médica"),
                    ("SIMULADO", "Simulado"),
                    ("AMBAS", "Integrada E Reposição"),
                ],
                default="INTEGRADA",
                help_text="Indique se a questão pode ser usada na Integrada, Reposição ou em ambas.",
                max_length=10,
            ),
        ),
    ]
