# Generated by Django 5.2.6 on 2026-04-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0009_alter_questao_uso_prova"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: 2025.1, 2025.2", max_length=20, unique=True
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Marque como ativo para o semestre corrente.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["-nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="aiprompt",
            options={},
        ),
        migrations.AlterField(
            model_name="aiprompt",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="aiprompt",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="aiprompt",
            name="texto_prompt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="eh_correta",
            field=models.BooleanField(
                default=False, help_text="Marque se for a correta."
            ),
        ),
        migrations.AlterField(
            model_name="alternativa",
            name="texto",
            field=models.CharField(help_text="Texto da alternativa.", max_length=500),
        ),
        migrations.AlterField(
            model_name="questao",
            name="enunciado",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens_questoes/"
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="justificativa",
            field=models.TextField(
                default="Sem justificativa",
                help_text="Justificativa da resposta correta e dos distratores.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questao",
            name="professor_email",
            field=models.EmailField(default="Sem professor", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questao",
            name="professor_nome",
            field=models.CharField(default="Sem professor", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questao",
            name="proposicao_dois",
            field=models.TextField(
                blank=True,
                help_text="Usado apenas para questões de Asserção-Razão.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente de Validação"),
                    ("APROVADA", "Aprovada"),
                    ("REPROVADA", "Reprovada"),
                ],
                default="PENDENTE",
                help_text="Questões aprovadas serão usadas nas provas. Reprovadas geram notificações de status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="questao",
            name="texto_base",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questao",
            name="uso_prova",
            field=models.CharField(
                choices=[
                    ("INTEGRADA", "Apenas Prova Integrada"),
                    ("SIMULADO", "Apenas Simulado"),
                    ("REPOSICAO", "Apenas Reposição"),
                    ("RESIDENCIA", "Apenas Residência"),
                    ("AMBAS", "Integrada e Reposição"),
                ],
                default="INTEGRADA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="periodo",
            name="semestre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos",
                to="questoes.semestre",
            ),
        ),
    ]
