# Generated by Django 5.2.17 on 2026-10-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0010_semestre_alter_aiprompt_options_alter_aiprompt_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_receipt', to='questoes.questao')),
            ],
        ),
    ]
