# Generated by Django 5.2.17 on 2026-10-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0012_preserve_receipts_and_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nome',
            field=models.CharField(help_text='Ex: 1º Período', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(fields=('semestre', 'nome'), name='periodo_nome_por_semestre'),
        ),
    ]
