# Generated by Django 5.2.17 on 2026-10-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0013_alter_periodo_nome_periodo_periodo_nome_por_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='consolidado_em',
            field=models.ForeignKey(blank=True, editable=False, help_text='Cadastro compartilhado que substitui este componente, preservando links antigos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastros_unificados', to='questoes.componentecurricular'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para arquivar um cadastro de período.'),
        ),
    ]
